- name: variables  declare # name of the yaml 
  hosts: webservers        # host of the yaml
  become: True
  become_user: ubuntu  # name of the host
  tasks:                               # tasks to perform automation for project
    - name: install the apache tomcat
      yum:
        name: httpd
        state: present
      tags:
        - install
    - name: start the the apache server
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - start
    - name: copy the code from souce to destination to and  deploy it
      copy:
        src: index.html
        dest: /var/www/html/
      tags:
       - deploy  
        